### ISSUE TITLE
Carousel responsiveness 

### ISSUE THREAD

**Issue by rasom** [status-im/wallet#6]
Carousel is hidden abit by the next `:div` inside `!browse` suggestions (maybe it is because webview's height is lower then it could be in the browser)
<img src="https://cloud.githubusercontent.com/assets/2364994/17393379/fd969e46-5a2b-11e6-93dd-5111ba9c04d6.png" width=275 />

Should be like here (except `Wallets` should not be moved up):
<img src="https://cloud.githubusercontent.com/assets/2364994/17393333/aa68b240-5a2b-11e6-91a6-4d7232bef320.png" width=275 />

**Comment by alwx** [comment]
Carousel has been rewritten.
https://github.com/status-im/wallet/pull/20
